name: Bug report
description: Create a report to help us improve
labels: [ 'bug' ]
body:
  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to reproduce
      description: Outline the steps to reproduce the behavior.
      placeholder: >
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: input
    attributes:
      label: WordPress version
      description: What version of WordPress was this tested on?
    validations:
      required: true

  - type: input
    attributes:
      label: Code Snippets version
      description: What version of Code Snippets was this tested on?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Code Snippets license
      description: Was this tested on the core free plugin, or with Code Snippets Pro?
      multiple: true
      options:
        - Core (free)
        - Pro
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
