blank_issues_enabled: true
contact_links:
  - name: ❓ Support Question
    url: https://help.codesnippets.pro/
    about: For Code Snippets users who need assistant and have general usage questions.
  - name: 💎 Premium Support - For customers only
    url: https://help.codesnippets.pro/
    about: If you have an active license you are entitled to premium support.
  - name: 🗨️ Code Snippets Facebook Community
    url: https://www.facebook.com/groups/codesnippetsplugin
    about: The main Facebook group where all kinds of users come together to help each other.
  - name: 📚 Code Snippets Documentation
    url: https://help.codesnippets.pro/
    about: Anything you need to know about Code Snippets and what to do if you may have an issue.
